import express from 'express';
import { protect } from '../middleware/auth.js';
import { createProject, getProjects, getProject, updateProject, deleteProject } from '../controllers/projectController.js';
const router = express.Router();
router.use(protect);
router.post('/', createProject);
router.get('/', getProjects);
router.get('/:id', getProject);
router.put('/:id', updateProject);
router.delete('/:id', deleteProject);
export default router;